import { categories } from "./courses";

/**
 * All course-combinations
 */
const courseCombinations = [
  {
    id: 0,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Mathematik,
      categories.Deutsch,
    ],
    grundkurse: [
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 1,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Naturwissenschaft,
      categories.Deutsch,
    ],
    grundkurse: [
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 2,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Leistungskurs,
    ],
    grundkurse: [
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 3,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Fremdsprache,
      categories.Mathematik,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 4,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Fremdsprache,
      categories.Naturwissenschaft,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 5,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Leistungskurs,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 6,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Mathematik,
      categories.Naturwissenschaft,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 7,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Mathematik,
      categories.Informatik,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 8,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Mathematik,
      categories["Gesellschaftswissenschaftliches Fach"].Leistungskurs,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 9,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Naturwissenschaft,
      categories.Naturwissenschaft,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 10,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Naturwissenschaft,
      categories["Gesellschaftswissenschaftliches Fach"].Leistungskurs,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 11,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Naturwissenschaft,
      categories.Informatik,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 12,
    leistungskurse: [
      categories.Mathematik,
      categories.Naturwissenschaft,
      categories.Deutsch,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 13,
    leistungskurse: [
      categories.Mathematik,
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Leistungskurs,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 14,
    leistungskurse: [
      categories.Mathematik,
      categories.Naturwissenschaft,
      categories["Gesellschaftswissenschaftliches Fach"].Leistungskurs,
    ],
    grundkurse: [
      categories.Deutsch,
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 15,
    leistungskurse: [
      categories.Naturwissenschaft,
      categories.Naturwissenschaft,
      categories.Deutsch,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 16,
    leistungskurse: [
      categories.Mathematik,
      categories.Deutsch,
      categories.Informatik,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 17,
    leistungskurse: [
      categories.Naturwissenschaft,
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Leistungskurs,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 18,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Mathematik,
      categories.Sport,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 19,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Mathematik,
      categories.Religionslehre.Leistungskurs,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 33,
  },
  {
    id: 20,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Mathematik,
      categories["Künstlerisches Fach"].Leistungskurs,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 21,
    leistungskurse: [
      categories.Naturwissenschaft,
      categories.Deutsch,
      categories.Informatik,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 22,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Naturwissenschaft,
      categories.Sport,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Religionslehre.Grundkurs,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 23,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Naturwissenschaft,
      categories.Religionslehre.Leistungskurs,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 2"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 24,
    leistungskurse: [
      categories.Fremdsprache,
      categories.Naturwissenschaft,
      categories["Künstlerisches Fach"].Leistungskurs,
    ],
    grundkurse: [
      categories.Deutsch,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 25,
    leistungskurse: [
      categories.Mathematik,
      categories.Deutsch,
      categories.Sport,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 1"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 26,
    leistungskurse: [
      categories.Mathematik,
      categories.Deutsch,
      categories.Religionslehre.Leistungskurs,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 1"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 27,
    leistungskurse: [
      categories.Mathematik,
      categories.Deutsch,
      categories["Künstlerisches Fach"].Leistungskurs,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Naturwissenschaft,
      categories.Religionslehre.Grundkurs,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
    ],
    pflichtstunden: 32,
  },
  {
    id: 28,
    leistungskurse: [
      categories.Naturwissenschaft,
      categories.Deutsch,
      categories.Sport,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Religionslehre.Grundkurs,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 1"],
    ],
    pflichtstunden: 35,
  },
  {
    id: 29,
    leistungskurse: [
      categories.Naturwissenschaft,
      categories.Deutsch,
      categories.Religionslehre.Leistungskurs,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 1"],
    ],
    pflichtstunden: 35,
  },
  {
    id: 30,
    leistungskurse: [
      categories.Naturwissenschaft,
      categories.Deutsch,
      categories.Religionslehre.Leistungskurs,
    ],
    grundkurse: [
      categories.Fremdsprache,
      categories["Gesellschaftswissenschaftliches Fach"].Grundkurs,
      categories.Mathematik,
      categories.Sport,
      categories["Verpflichtende Kurse 1"],
      categories["Verpflichtende Kurse 1"],
    ],
    pflichtstunden: 33,
  },
];
